services:
  graylog:
    image: "graylog/graylog:${GRAYLOG_VERSION}"
    container_name: "graylog-app-${ENV}"
    hostname: "server"
    depends_on:
      mongodb:
        condition: "service_healthy"
      opensearch:
        condition: "service_healthy"
    entrypoint: "/usr/bin/tini -- /docker-entrypoint.sh"
    environment:
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2}"
      GRAYLOG_SERVER_JAVA_OPTS: "${GRAYLOG_SERVER_JAVA_OPTS}"
      GRAYLOG_HTTP_EXTERNAL_URI: "${GRAYLOG_HTTP_EXTERNAL_URI}"
      GRAYLOG_HTTP_BIND_ADDRESS: "${GRAYLOG_HTTP_BIND_ADDRESS}"
      GRAYLOG_MESSAGE_JOURNAL_ENABLED: "${GRAYLOG_MESSAGE_JOURNAL_ENABLED}"
      GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE: "${GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE}"
      GRAYLOG_MESSAGE_JOURNAL_MAX_AGE: "${GRAYLOG_MESSAGE_JOURNAL_MAX_AGE}"
      GRAYLOG_PROCESSBUFFER_PROCESSORS: 5
      GRAYLOG_OUTPUTBUFFER_PROCESSORS: 4
      GRAYLOG_INPUTBUFFER_PROCESSORS: 2
      GRAYLOG_RING_SIZE: 131072
      GRAYLOG_OUTPUT_BATCH_SIZE: 750
      GRAYLOG_OUTPUT_FLUSH_INTERVAL: 1

      GRAYLOG_PROMETHEUS_EXPORTER_ENABLED: "true"
      GRAYLOG_PROMETHEUS_EXPORTER_BIND_ADDRESS: "0.0.0.0:9833"

      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_ROOT_TIMEZONE: "Asia/Bangkok"
      TZ: "Asia/Bangkok"

    ports:
      - "0.0.0.0:9000:9000/tcp" # Web UI
      - "0.0.0.0:514:514/udp" # Syslog UDP
    volumes:
      - "${GRAYLOG_JOURNAL_PATH}:/usr/share/graylog/data/journal"
      - "${GRAYLOG_LOOKUPS_PATH}:/etc/graylog/server/lookup:ro"
    networks:
      - "logserver_net"
    restart: "unless-stopped"
    deploy:
      resources:
        limits: { cpus: '4.0', memory: 6g }
        reservations: { cpus: '2.0', memory: 3g }
    healthcheck:
      test: 
        - "CMD-SHELL"
        - "curl -fsS http://localhost:9000/api/system/lbstatus || exit 1"
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s

  mongodb:
    image: "mongo:${MONGODB_VERSION}"
    container_name: "gl-mongodb-${ENV}"
    hostname: "mongodb"
    volumes:
      - "${MONGODB_DATA_PATH}:/data/db"
      - "${MONGODB_BACKUP_PATH}:/backups"
    networks:
      - "logserver_net"
    restart: "unless-stopped"
    environment:
      - "TZ=Asia/Bangkok"
    deploy:
      resources:
        limits: { cpus: '1.0', memory: 2g }
        reservations: { cpus: '0.5', memory: 1g }
    healthcheck:
      test: 
        - "CMD"
        - "mongosh"
        - "--eval"
        - "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  opensearch:
    # image: "opensearchproject/opensearch:${OPENSEARCH_VERSION}"
    build:
      context: ./images/opensearch
      args:
        OPENSEARCH_VERSION: "${OPENSEARCH_VERSION}"
        OPENSEARCH_PROM_EXPORTER_VERSION: "${OPENSEARCH_PROM_EXPORTER_VERSION}"
    image: "tasco-logserver/opensearch:${OPENSEARCH_VERSION}-prom${OPENSEARCH_PROM_EXPORTER_VERSION}"
    container_name: "gl-opensearch-${ENV}"
    hostname: "opensearch"
    environment:
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
      - "OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS}"
      - "TZ=Asia/Bangkok"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "${OPENSEARCH_DATA_PATH}:/usr/share/opensearch/data"
      - "${OPENSEARCH_SNAP_PATH}:/usr/share/opensearch/snapshots"
      - "${OPENSEARCH_CONFIG_PATH}:/usr/share/opensearch/config/opensearch.yml:ro"
    networks:
      - "logserver_net"
    ports:
      - "127.0.0.1:9200:9200" # API (internal host only)
    restart: "unless-stopped"
    deploy:
      resources:
        limits: { cpus: '6.0', memory: 22g }
        reservations: { cpus: '3.0', memory: 10g }
    healthcheck:
      test:
        - "CMD-SHELL"
        - "curl -s http://localhost:9200/_cluster/health | grep -qE '\"status\":\"(green|yellow)\"'"
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
