apiVersion: 1

datasources:
  - name: Prometheus Host Metrics
    uid: ds-prometheus-host-metrics
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
